# This is a dedicated workflow for the end-to-end test suite, which requires a browser
# and static assets setup. We serve the `wewerewondering` client-side rendered application
# with our axum app (which we only use for data API in production environment), then open
# the applcation and perform certain actions impersonating both sides - a host and a guest -
# as befits a decent puppet show.
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: e2e
jobs:
  test:
    runs-on: ubuntu-latest
    name: ubuntu-latest / stable / tls
    defaults:
      run:
        working-directory: ./server
    env:
      WEBDRIVER_PORT: 4444
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: Install browser engine and web driver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 132
          install-chromedriver: true
      - name: Launch web driver in background
        run: chromedriver --port=${{ env.WEBDRIVER_PORT}} &
      - name: Run tests
        env:
          USE_DYNAMODB: local
        run: cargo t --release --test e2e -- --include-ignored
